### ISSUE TITLE
(multiplayer) game setting menu not accessible

### ISSUE THREAD

**Issue by dehjvg** [stijnwop/manualAttach#102]
wopster was saying everyone on the server had the freedom to enable or disable the manaulattachment mod.

but because the option to turn it on and of is in the game settings menu you need to be logged in to get acces to that menu.

so at thiis moment everyone that joins the server is forced to use it see the screenshot below to see wat a not logged in player sees on multiplayer

![image](https://user-images.githubusercontent.com/47279976/144106424-5b542fd0-dbc8-449a-b8ad-1b30b0180aed.png)

**Comment by stijnwop** [comment]
Pushed a fix :)

**Comment by dehjvg** [comment]
to bad its not fixed

if i seen it right you used the tab train setting witch is also not vissible in multiplayer servers
but it did move from the game settings to the general settings so that part is fixed


![fsScreen_2021_11_30_20_37_28](https://user-images.githubusercontent.com/47279976/144115897-7a152280-1310-40d5-9c54-f7fb33bfca1f.png)

**Comment by stijnwop** [comment]
Hmm, thought a deep clone would not be affected by that behaviour.

I used the checkUseEasyArmControl now, wonder if that does show? If not something else needs to be fixed.

**Comment by dehjvg** [comment]
just tested it and its working fine now
