### ISSUE TITLE
Der Ballenhänger Farmtech DPW1800 lässt sich nicht ankuppeln

### ISSUE THREAD

**Issue by drgraubrot** [stijnwop/manualAttach#109]
Deaktiviert man manual attach lässt sich der Hänger problemlos anhängen. Mit aktiviertem Mod gibt es keine Chance den Hänger an den Traktor zu bekommen. Vielleicht als Hinweis, der Hänger nutzt die untere Anhängerkupplung des Traktors.

**Comment by Pleasure0102** [comment]
cannot reproduce, working fine for me, check video (Kann ich nicht bestätigen, funktioniert normal bei mir, siehe video)
https://streamable.com/nuf3om

**Comment by drgraubrot** [comment]
lustig. mit einem Deutz geht es bei mir auch.... mit dem MF 8s davor geht es nicht

**Comment by Pleasure0102** [comment]
confirmed, attaching does not work for the DPW1800 + MF 8S

**Comment by drgraubrot** [comment]
aye sir ;) attaching the dpw1800 to the claas axion 960-920 is also not possible

**Comment by Pleasure0102** [comment]
it will maybe help if you can try out some more, and put together a list :)

**Comment by drgraubrot** [comment]
i think the two combos are enough to figur out a similarity between both. this should narrow down the possibilities quite a bit and i have a lot of land to farm :)

**Comment by stijnwop** [comment]
Optimized the vehicle search method for FS22 (some minor things changed)
Now it seems to work

**Comment by drgraubrot** [comment]
problem is solved, thanks a lot and keep up the good work
