### ISSUE TITLE
Game crash after quit with manualAttach enabled

### ISSUE THREAD

**Issue by Celusendon** [stijnwop/manualAttach#110]
Hi!

If you are running the game (FS22) in standard fullscreen (not exclusive) with only manualAttach enabled, the game crashes after you quit from a savegame, but there are no visible errors in the log.

I'm not 100% sure the mod itself causes this, but if I disable manualAttach, this issue won't happen.

If somebody uses exclusive fullscreen, this issue never happens.

**Comment by Pleasure0102** [comment]
this happens at the moment with every mod that uses scripts, nothing wopster can do, this has to be fixed by giants, afaik they are aware of this.

**Comment by stijnwop** [comment]
Yes this is a game bug and GIANTS knows about it.
Hopefully fixed with the patch 1.2.
