### ISSUE TITLE
Bug with big bags, frontloader

### ISSUE THREAD

**Issue by Horozor** [stijnwop/manualAttach#111]
Use baglifter. 
Attach 2 bags 
then press tab or E to exit from vehicle. 
Character disappear, lose controls, can't exit form tractor or tab to another vehicle

2021-12-02 19:32 Error: Running LUA method 'update'.
2021-12-02 19:32 dataS/scripts/vehicles/specializations/AttacherJoints.lua(3449) : attempt to call method 'setAIVehicleObstacleStateDirty' (a nil value)

[Log](https://gist.github.com/Horozor/4d2f0eda49be615fb6aae73b11349f85)

**Comment by Pleasure0102** [comment]
i can reproduce. Checking some more combos

**Comment by stijnwop** [comment]
Believe thats the gamebug with baglifters

**Comment by Horozor** [comment]
@stijnwop 
All good without MA

**Comment by Pleasure0102** [comment]
nope, just tested without MA and got the same problem, giants bug

**Comment by Horozor** [comment]
Ah, really Giants bug. Sorry
