### ISSUE TITLE
MP/DEDI Server - Player settings

### ISSUE THREAD

**Issue by CurtisFeatures** [stijnwop/manualAttach#113]
This probably isn't a bug and may not be able to be changed. 

I installed the mod on my pedi today and told the players that they can either choose to have it on or off. The issue is that you have to be logged in as admin to get to the screen to enable/disable the feature which is not practical as I can't give the admin password out to everyone. 

If this cannot be changed to the user settings area then is there an XML that I can update manually to turn it on and off for people or are the settings stored client side?

Thanks
Jamie

**Comment by dehjvg** [comment]
in the github version this isseu is already fixed.

only the one on modhub still needs to get a update

**Comment by CurtisFeatures** [comment]
> in the github version this isseu is already fixed. #102
> 
> only the one on modhub still needs to get a update

Thats by stupid fault for not checking the closed issues
