### ISSUE TITLE
Manual Attach - Herbicide Spraying not working

### ISSUE THREAD

**Issue by StussyEx** [stijnwop/manualAttach#115]
The manual attach does not work for the Spraying (herbicide) manually or with AI or on missions, When all hoses are attached, it does not recognise the field to start spraying.
Tested on all maps, with different sprayers.

**Comment by stijnwop** [comment]
Did you also check without Manual Attach?

**Comment by StussyEx** [comment]
Yes, without manual installed it works fine.

**Comment by dehjvg** [comment]
we got no isseus with herbicide sprayeing with this mod on using the hardi 1200 sprayer and front tank 

(are you sure you connected the pto as well?)

**Comment by StussyEx** [comment]
You know what, I do not think I did, schoolboy error, apologies!
