### ISSUE TITLE
Problem with ELHO Scorpio 550

### ISSUE THREAD

**Issue by Markus33-ITA** [stijnwop/manualAttach#130]
Hi. I remember that with ELHO Scorpio 550 tube connection worked. I connect the tow with the Q button and the tool works. It opens even though the hoses are not connected

![fsScreen_2021_12_26_22_48_52](https://user-images.githubusercontent.com/96330304/147420867-ce9acb81-bfcb-45d1-a8e9-6d22f8fcab3f.png)

**Comment by stijnwop** [comment]
Cannot reproduce with the latest version.
