### ISSUE TITLE
Manual Attach mostly broken since Patch 1.2 

### ISSUE THREAD

**Issue by alexanderweide** [stijnwop/manualAttach#132]
Hey this probably fits also to the issue in:

https://github.com/stijnwop/manualAttach/issues/124

Since patch 1.2 by giants the manual attach mod dosent work anymore properly on dedicated servers, almost every day deataching of Tools and trailers is not possible anmyore. Only solution is to reset the given trailer or tool.

Also the menu button is missing since patch 1.2

mfg

**Comment by s4t4n** [comment]
Still works fine for me, check if there is a conflict with another script mod.

**Comment by alexanderweide** [comment]
> Still works fine for me, check if there is a conflict with another script mod.

i checked all mods the entire day even with all mods deactivated i still get the same issue, that manual attach will not de-attach some tools or trailers. After de-installation of the mod the issue was gone. on all objects that where not attached with manual attach. I can clearly see that tools attached with manual attach are producing errors in the game, i dont checked LOG. for what ever reason. Only resettings/reconfigure of each tool that was affected after removing of manual attach worked so far. Objects of same kind, even same tools that where not even used with manual attach are clearly unaffected. 

thats all what i can say. And this is happening since Giants Patch 1.2.02

**Comment by alexanderweide** [comment]
Update: I close this isuse since it turned out on Steam Discussions that this is a bug from the native game, it seems to get worse with the mod but its a native bug of the game.
