### ISSUE TITLE
Lemken Solitair 12, can´t connect hoses

### ISSUE THREAD

**Issue by OchNeeOder** [stijnwop/manualAttach#134]
I can attach the seeder to the tractor (pressing Q) but can´t connect the hoses of Lemken Solitair 12 (seeder, basegame), there´s no prompt to press and hold Y in the F1 menu.

I´ve started a new savegame with only Manual Attach in the mod folder and tested several other seeders (Grimme GL420, Grimme GL860, Kinze 3665 Blue Drive, Kuhn BTFR 6030 + HR 6040 RCS, Nordsten NS30 and Väderstadt Rapid A800S) and all of them work perfectly fine.

**Comment by stijnwop** [comment]
This is an issue with the game as the Lemken does not seem to be setup correctly with the hoses.

Try it without MA, the hoses won't attach that way either.. will be probably be fixed with the next patch.
