### ISSUE TITLE
ManualAttachConnectionHoses.lua:185: attempt to index local 'spec' (a nil value)

### ISSUE THREAD

**Issue by criss20ster** [stijnwop/manualAttach#145]
I have trouble in this mod. I have this community in game 

E:/ModyFS22/FS22_manualAttach/src/vehicle/ManualAttachConnectionHoses.lua:185: attempt to index local 'spec' (a nil value)

**Comment by Williwillswisse** [comment]
I had this error too when I load the FS22_Beaverator Mod.
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=250368&title=fs2022

I'm not the great lua-scripter but for testing I changed the following in the ManualAttachConnectionHoses.lua:
![image](https://user-images.githubusercontent.com/47098121/185588092-c6ca8fc3-1c55-4de6-b865-44547dfb7bd8.png)

After this no more error logs.
Maybe @stijnwop can take a look at this ...
