### ISSUE TITLE
detectionTrigger has wrong collisions and blocks other mods

### ISSUE THREAD

**Issue by Achimobil** [stijnwop/manualAttach#152]
As the titel says, the detectionTrigger in the mod has the wrong collision bit 13 which tells it is a vehicle.
Also it has the in LS22 obsolete collision bits 22 and 23.
The marking as vehicles blocks the free area for other mods and functions.
So when a player is next to a pallet spawner, the pallet could not be spawned becaue the spawn area is blocked.
Also the existint autoloaders are blocked by this wrong collision.

On my side I changed the collision mask and the mod seems o work without blocking the spawners.
Can this be corrected with a new release? 
Or should I change it and send per pull request?

Greetings
Achim

**Comment by stijnwop** [comment]
Done
