### ISSUE TITLE
header trailer

### ISSUE THREAD

**Issue by xXDorfkindXx** [stijnwop/manualAttach#157]
Hello,

with the new version there are problems with the header trailer,
the trailers always brake.

sry for my english

**Comment by KITT3000** [comment]
because you didn't connect the hose from the lights, but this should be fixed in the upcoming version

**Comment by xXDorfkindXx** [comment]
the electic hose is on the tractor.

**Comment by KITT3000** [comment]
try version 2.2.0.0 from the Releases tab

**Comment by stijnwop** [comment]
Ah wait, correct let me fix that :D

**Comment by KITT3000** [comment]
🤦‍♂️ that's how it is when I don't read exactly what someone writes

sry for spam

**Comment by stijnwop** [comment]
Pushed a fix

**Comment by xXDorfkindXx** [comment]
thanks it works again.

**Comment by s4t4n** [comment]
the fix work now, but the airHoses when exist at foragemixerwagons, it connect it but without function, e.g. the connect air sound script doesn't play a sound and the filltype "air" get not more usage becourse the mixer trailer needs
