### ISSUE TITLE
Issue with new Version 2.2.0.0

### ISSUE THREAD

**Issue by Inoque71** [stijnwop/manualAttach#159]
Hi, I found this issue, probably could be able to found in others implements.
This test I done with any mods, vanila map.
Any tractor not more with 280Hp and the seeder Vaderstad Rapid A800s.
The tractor don't have power to pull the seeder (keep 13 /16 khp).

I select on/off manual attach in game settings, to connect all the hoses but nothing happens.

I done the same test with version 2.0.0.0.
No problem found

**Comment by alfi0212** [comment]
Hi, same issue here - tried with Fendt 930 Gen 7 and Krone MX.

**Comment by stijnwop** [comment]
Did you actually try the latest push or the released version? :)
Cause there was a little fix after the release (https://github.com/stijnwop/manualAttach/issues/157)
Also if you mention vehicles, either list them as modhub links or give examples with vanilla vehicles..

**Comment by alfi0212** [comment]
Hi, - i downloaded your latest version - now i tried the latest push and the issue is gone - thx!!!

**Comment by Inoque71** [comment]
Hi, is working
