### ISSUE TITLE
Issues after Update 

### ISSUE THREAD

**Issue by MRNOBODY515** [stijnwop/manualAttach#161]
One example for issues with the latest Update. No Mods. New Savegame. Only Manual Attach in use. Buy the Hardy Aeon. It will be delivered like this. 
![received_5577246869046721](https://user-images.githubusercontent.com/114937809/226174660-54f6301a-bec6-48a7-9e69-f126b4ad757f.jpeg)

Also have problems with a Modhub lowbed trailer from HR Modding (Goldhofer STZ-VP 3). This one can be extendet in lenght. After the update it's always retracted. Before the update everything was fine.

**Comment by stijnwop** [comment]
Pushed a fix for this issue.

**Comment by MRNOBODY515** [comment]
Thank you Stijn! Your mods are always great.  Thanks for that!
