### ISSUE TITLE
Unable to dump anything out of trailers

### ISSUE THREAD

**Issue by suicidepimpin** [stijnwop/manualAttach#171]
Only noticed this about a week ago, playing on Saskatchewan I went to sell grain and was unable to tip. I disabled Manual Attach from mod list and it worked perfectly fine.

**Comment by stijnwop** [comment]
From the mod description:

Without attached connection hoses the following can occur:
- You won't be able to control hydraulics (e.g. moving parts, folding, use ridge markers etc)
- You won't be able to use the lights.
- Brakes will be blocked.

Did you check if the hoses are attached? As thats the whole idea of the mod...

**Comment by suicidepimpin** [comment]
Yes I have hoses attached. Been using this mod since '19; If I have to screen record to prove this let me know. It tells me whatever I am hauling cannot be tipped into the silo. Weather its my own silo or a sell point.

I'm not that dumb.
