### ISSUE TITLE
LUA problem

### ISSUE THREAD

**Issue by criss20ster** [stijnwop/manualAttach#173]
After uploading the latest version, the game suddenly throws up lua script problems in red

**Comment by TobiasF92** [comment]
Would be usefull to add the log. (Server and Client if in Multiplayer) ;)

**Comment by criss20ster** [comment]
[log.txt](https://github.com/stijnwop/manualAttach/files/12365909/log.txt)

**Comment by Evilman2517** [comment]
![Screenshot_20230817_090503_HTML Viewer](https://github.com/stijnwop/manualAttach/assets/35241745/7d6efc90-c9a2-4d63-963e-0e9cdb747f7c)
No wonder if you load  a mod two times. Delete one and have fun

**Comment by TobiasF92** [comment]
And try to remove unused mods, pretty sure you dont use every of your ~2000 mods loaded ;)

**Comment by criss20ster** [comment]
sorry for the trouble . Indeed, I did not notice it works

**Comment by criss20ster** [comment]
> And try to remove unused mods, pretty sure you dont use every of your ~2000 mods loaded ;)

Yes, that's right, I just need to catalog it somehow, and I don't know how, because some are cool and some would be ok to play with.
