### ISSUE TITLE
Fix controller input

### ISSUE THREAD

**Issue by stijnwop** [stijnwop/manualAttach#24]
Attach/detach hoses and pto is on the same inputs as attach/detaching the implement

**Comment by breadje** [comment]
this change did not change anything for me on my steam controller. The PTO and vehicle flicker between connected and disconnected state constantly when using the gamepad. I do not have this issue when I'm using the keyboard.

**Comment by KITT3000** [comment]
@breadje If you previously had this mod then the assigned keys remained old but you can change these keys yourself in the game.

**Comment by breadje** [comment]
Ah, yep I should've guessed that.
