### ISSUE TITLE
Dedi - Mowers only work with detached PTO

### ISSUE THREAD

**Issue by Evilman2517** [stijnwop/manualAttach#33]
Hello,

we occured an issue. On our Dedi we could only activate the mowers when the PTO was detached.
With attached PTO the mower would deativate itself instantly.

Logs were clean, when needed I can provide the client and server log

**Comment by stijnwop** [comment]
Should be fixed with the last commit.

**Comment by Evilman2517** [comment]
Hey,
sorry for my late reply. Tested it today, and the mowers work fine now. Thank you very much for the quick fixing
