### ISSUE TITLE
trigger zone attachment

### ISSUE THREAD

**Issue by breadje** [stijnwop/manualAttach#34]
Hi, unfortunately the change to the trigger points led to some very tight trigger places. I can attach a tool when I'm standing against the back wheels, but I can not attach anything when I'm standing slightly behind them actually looking at the 3point hitch. It is more or less guessing now if I'm in the trigger zone or not.

**Comment by cwattyeso** [comment]
I too am using the version of the mod found here on the GitHub rather then the one on the in game ModHub. I too am experiencing very weird placement for the trigger to attach and couple up equipment. If I go to the actual rear of a tractor to connect up a piece of equipment I get nothing in the help menu:
![vlcsnap-2019-05-02-09h09m01s301](https://user-images.githubusercontent.com/13921716/57063156-332fd380-6cba-11e9-821b-087157f7a7f7.png)

If however I move myself to be more or less in line with the Rear Wheel Hub of the Vehicle I get the pop-up to attach the equipment:
![vlcsnap-2019-05-02-09h08m45s486](https://user-images.githubusercontent.com/13921716/57063193-55c1ec80-6cba-11e9-8989-aa5fc63e12a7.png)

To then attach a PTO or any Hoses or Cables, I found I need to then turn and look slightly towards the front of the Tractor to get the trigger to detect and the help window to display the tool tip for connecting the power takeoff or hoses:
![vlcsnap-2019-05-02-09h09m10s060](https://user-images.githubusercontent.com/13921716/57063253-86a22180-6cba-11e9-95c1-4a1e37e9bd98.png)

So for the time being I am disabling the mod, as much as I like it adding that extra bit of gameplay and a bit more realism and immersion, if you can't attach and make the equipment connections from the right spot and the logical place, and instead after hunt all round the vehicles or tools looking for the trigger it's a bit too frustrating to use at the minute.

**Comment by Jeytav** [comment]
yes the translation of the trigger has been moved from -1 to -2.5 which means you can't see if you actually attach the hoses, pto and machine properly changing "setTranslation(self.trigger, 0, 0, -2.5)" to "setTranslation(self.trigger, 0, 0, -1.5)" in misc/ManualAttachDetectionHandler.lua in line 99, will move it far enough back to be able to look and see the stuff getting attached.

**Comment by stijnwop** [comment]
@breadje 
@cwattyeso 
@Jeytav 

Please test again, I did some optimizations on the while detection mechanism.

**Comment by Jeytav** [comment]
Right did a test and is a lot better imo. 11/10
