### ISSUE TITLE
Synchronize attach state of PTO and connection hose on player join.

### ISSUE THREAD

**Issue by Evilman2517** [stijnwop/manualAttach#35]
Hello,

when I attach a crops header to a combine (fully, with PTO), leave the server and join again, I have to reattach the PTO again.

No big, just wanted to mention it

**Comment by stijnwop** [comment]
I see, thanks. 👍

**Comment by stijnwop** [comment]
Should be fixed.

**Comment by stijnwop** [comment]
@Evilman2517 please re-test.
