### ISSUE TITLE
Can't attach a maize header to combine

### ISSUE THREAD

**Issue by Evilman2517** [stijnwop/manualAttach#36]
Hello, with activated manual attach I could't attach a maize header to a combine. After deactivating the mod everything worked fine.
Tested with the original small Giants Case combine (Modhub) and the two small maize header.
There were no errors, I simply didn't got the option to attach it (inside or outside of the combine)

Greetings

**Comment by stijnwop** [comment]
What corn header exactly?

**Comment by Evilman2517** [comment]
Tested it with both small headers from the base game, Capello and Ziegler

**Comment by stijnwop** [comment]
#42 
Most likely related.

**Comment by stijnwop** [comment]
@Evilman2517 please re-test.

**Comment by Evilman2517** [comment]
Hi, sorry I didn't reply earlier. I just tested my reported bug and could't reproduce it. Issue solved, bug closed, everything fine ;-)
