### ISSUE TITLE
Anderson DLC XTractor "freezed"

### ISSUE THREAD

**Issue by CityFarmerDE** [stijnwop/manualAttach#37]
If I buy/lease or restart a savegame, the Anderson DLCs XTractors can´t be folded/unfolded and lights can´t be switched. They have to be attached and detached to a tractor first. 
If I end game with the wrappers unfolded they can´t be attached at the next game start because the hitch is stored under the baler. 

Tested with manualAttach 1.0.1.0

**Comment by stijnwop** [comment]
Fixed my man.

**Comment by CityFarmerDE** [comment]
works for me too. thx
