### ISSUE TITLE
[BUG] Gamepad let me detach implements inside the vehicle

### ISSUE THREAD

**Issue by turbostar190** [stijnwop/manualAttach#38]
When I attach an implement on the tractor, I can detach it inside the vehicle using the A button on gamepad.
Q key on keyboard doesn't work, how it should be.

Tried on a new savegame with only MA enabled.

A little video here: https://youtu.be/fIty2KdWe8I

**Comment by Evilman2517** [comment]
Hey, I can confirm this behavior

**Comment by stijnwop** [comment]
Mm, seems like I need to force overwrite the attach action event.

**Comment by turbostar190** [comment]
Last commit didn't solve the issue

**Comment by stijnwop** [comment]
Lol, this literally blocks the entire input event. Already had a feeling that this is vanilla related.. need to investigate further.

**Comment by turbostar190** [comment]
Solved
