### ISSUE TITLE
Issue after returning contract equipment

### ISSUE THREAD

**Issue by fowlplayuk** [stijnwop/manualAttach#40]
Describe the bug
Game freaks out after returning borrowed equipment from a contract job.
Hard to explain as it differs each time, but the most obvious thing I can see is that all the icons disappear from the map. Sometimes certain keys won't work. Manual Attach spams the log.

Noticed this originally on a modded map with quite a few mods installed, but tested on a vanilla map with ONLY Manual Attach enabled to isolate

To Reproduce
Take on contract using borrowed equipment - do work - complete contract to return equipment

Desktop (please complete the following information):

OS: Windows 10
FS patch version 1.3 Giants Disc copy

**Comment by stijnwop** [comment]
You're running the modhub version I assume?

**Comment by fowlplayuk** [comment]
Yes sir, downloaded through the mods section in game

**Comment by stijnwop** [comment]
Yeah, use the version here on GitHub. That one does not have the issue cause it's fixed. 👍

**Comment by fowlplayuk** [comment]
Ah, ok. Sorry, didn't noticed the difference in version number. Is this likely to be pushed to Modhub soon? Or has that been halted as I notice you mention it's still in development

**Comment by stijnwop** [comment]
Yeah will be pushed to modhub soonish .. when i have some time for it.

**Comment by fowlplayuk** [comment]
Nice. I won't take up any more of your time. I'll mark this as closed on my way out. Thanks for the help
