### ISSUE TITLE
Poetinger NOVACAT 301 ED don't work

### ISSUE THREAD

**Issue by ThisPf** [stijnwop/manualAttach#41]
Poetinger front mower with Fendt 500 Favorit. 
Manualattach Version from Modhub.

The front mower has no hoses, but does not work without hoses (can't unfold it). Can someone confirm this or is am I wrong?

Thanks for your great work.

**Comment by Wolfi-123** [comment]
It's the same as with the X8. It has got hoses, they are just not visible if you haven't attached them :D

**Comment by stijnwop** [comment]
Yeah I should start showing warning again I see.. that fendt 500 does not have hydraulic inputs infront. 
Try it on a different vehicle like the 6R or whatever.

**Comment by stijnwop** [comment]
Now the button should not show up anymore.

**Comment by ThisPf** [comment]
I test it in the evening. Many thanks

**Comment by ThisPf** [comment]
Works perfectly, many thanks
