### ISSUE TITLE
cant exclude attacer types

### ISSUE THREAD

**Issue by knuuud** [stijnwop/manualAttach#49]
Hi, in the new version of manualAttach I can't add attachers to ignore. Is there something I've missed? I used to add them in the manualattach.lua together with the lines like this
`ManualAttach.AUTO_ATTACH_JOINTYPES = {
    [mapJointTypeNameToInt("skidSteer")] = true,
    [mapJointTypeNameToInt("cutter")] = true,
    [mapJointTypeNameToInt("cutterHarvester")] = true,
    [mapJointTypeNameToInt("wheelLoader")] = true,
    [mapJointTypeNameToInt("frontloader")] = true,
    [mapJointTypeNameToInt("telehandler")] = true,
    [mapJointTypeNameToInt("loaderFork")] = true,
    [mapJointTypeNameToInt("hookLift")] = true,
    [mapJointTypeNameToInt("semitrailer")] = true,
    [mapJointTypeNameToInt("semitrailerHook")] = true,
    [mapJointTypeNameToInt("fastCoupler")] = true
    [mapJointTypeNameToInt("trailerLow")] = true
}`
the last one is the one I wanted to add as most tractors I use would in real life attach the low trailer attacher with a leaver dropping a hook from inside the tractor.

adding it was ok in the earlier versions, but now it throws this in log when starting the game:

`2019-07-12 20:24 Error: Running LUA method 'update'.
2019-07-12 20:24 H:/Dropbox/FarmingSimulator/Dedi19/FS19_manualAttach/src/loader.lua:50: attempt to index global 'ManualAttach' (a nil value)
`
any way I can do that and not get the error?

**Comment by stijnwop** [comment]
You forgot a comma most likely.

**Comment by knuuud** [comment]
sigh... problem solved.. sorry for the bother.... a facepalm is in its place I think.... :P Thanks
