### ISSUE TITLE
Noises for hoses and the shaft

### ISSUE THREAD

**Issue by Amadeo01** [stijnwop/manualAttach#52]
@wopster, great your manual attach!  Many Thanks.
I have no problems with it.

Can you still add connection noise for hoses and the shaft? 

Greetings Amadeo

**Comment by Alagoss** [comment]
Sounds good =P

**Comment by Amadeo01** [comment]
@wopster, perfekt! - Super ---> vielen Dank.

**Comment by stijnwop** [comment]
Are the sounds actually somewhat okayish?

**Comment by Amadeo01** [comment]
Oh ja, schon super! - Vielleicht (aber wirklich nicht erforderlich) für die Schläuche ein 3-fach: "Klack, klack, klack".  ;)
