### ISSUE TITLE
Can't detach Samson Agro D 12

### ISSUE THREAD

**Issue by DearJohny** [stijnwop/manualAttach#54]
Hey,

so I can't detach the Samson Agro from the PGII 25.

It always says "Lower xxx" but when I lower the Agro D12 than the implement unfolds and if you lower it, it automatically turns on, so after that you can't detach the connection hoses, because it says "First turn off xxx". 

Would be cool if this could be fixed, I use the V1.0.1.1.

But really gotta say thanks for this awesome mod, it's really cool.

**Comment by stijnwop** [comment]
@DearJohny okay fixed.
Please re-test.

**Comment by DearJohny** [comment]
Thank you very much!
Works like a charm. :)
