### ISSUE TITLE
Second Implement attachable

### ISSUE THREAD

**Issue by Evilman2517** [stijnwop/manualAttach#55]
When I want to detach an implement from the frontloader a nearby standing other implement can be attached, same with implements for the hydraulics. Issue occurs both in SP and MP (Dedi)

![fsScreen_2019_08_18_14_01_37](https://user-images.githubusercontent.com/35241745/63224187-e288ab80-c1c0-11e9-8cee-e5ae66862a63.png)

![fsScreen_2019_08_18_14_01_43](https://user-images.githubusercontent.com/35241745/63224190-e61c3280-c1c0-11e9-9603-9b1fe34e677a.png)

![fsScreen_2019_08_18_14_01_57](https://user-images.githubusercontent.com/35241745/63224192-eae0e680-c1c0-11e9-9cad-0fa3721a87e9.png)

[log.txt](https://github.com/stijnwop/manualAttach/files/3512987/log.txt)

Greetings

**Comment by stijnwop** [comment]
Thinking about it.. is this possible in the vanilla game?

**Comment by Evilman2517** [comment]
Just tested it, in vanilla it is not possible to attach a second implement when one is already attached

![fsScreen_2019_08_18_14_17_29](https://user-images.githubusercontent.com/35241745/63224354-1e247500-c1c3-11e9-9aa5-c6df29eaa283.png)

[log.txt](https://github.com/stijnwop/manualAttach/files/3513002/log.txt)

**Comment by stijnwop** [comment]
okay fixed, please retest.

**Comment by Evilman2517** [comment]
You Sir are awesome ;-)
Bug is fixed, tested in SP and MP, thank you very much
