### ISSUE TITLE
Issue with Claas DLC

### ISSUE THREAD

**Issue by Szmiti** [stijnwop/manualAttach#59]
Hello,

ManualAttach does not seem to work at all with the Tucano 580 combine with Corio 875C maize header from the Class DLC pack.  It seems only this combination has issues, as ManualAttach works perfectly with the same combine with the Vario 770 header _and_ the larger Lexion 8900 combine with both larger headers.

Szmiti

**Comment by stijnwop** [comment]
![fsScreen_2019_10_23_11_57_35](https://user-images.githubusercontent.com/12030020/67381606-747bae80-f58c-11e9-982a-6df091f7bc78.png)
![fsScreen_2019_10_23_11_57_45](https://user-images.githubusercontent.com/12030020/67381609-75acdb80-f58c-11e9-8c7c-b2d51721d5d8.png)

So I tried the combination.. with the MA version from modhub. I could attach it without problems.

**Comment by Szmiti** [comment]
You're right - sorry .... I hadn't removed _all_ my other mods - after removing (except the DLC and the mod map) I don't have any problems either - so it seems this is caused by another mod.  I will investigate and let you know out of interest.  Thanks !

**Comment by stijnwop** [comment]
No worries, great let me know 👍

**Comment by Szmiti** [comment]
OK, I have the culprit: Game Extension by Xentro - if I uncheck this, then no issue.  In any case it seems he's not developing it actively and I deleted it as I was only really keeping it for the ability to switch off the crosshairs - but that's a really minor thing I can live without ....

**Comment by stijnwop** [comment]
Weird indeed. When I find some time I will talk with Xentro about it. 
Thanks for figuring it out! :)
