### ISSUE TITLE
New Holland CR10.90 can not start

### ISSUE THREAD

**Issue by Rumspringa90** [stijnwop/manualAttach#60]
Hello,

I Can't start the New Holland CR10.90 i've get in a mission. Without the manualAttach mod i get from the ModHub in v1.0.1.1 its work. So its must a Problem with the Mod. There are no log entries

**Comment by stijnwop** [comment]
I assume you did read the description and added the PTO and connection hoses?

**Comment by Rumspringa90** [comment]
Oh noooo, I'm so stupid ...
with other combines I did not have that, so I did not think about it.
Thank you, great MOD!!!
