### ISSUE TITLE
Slurry tanks

### ISSUE THREAD

**Issue by Black4Howk** [stijnwop/manualAttach#67]
Hello everybody,
I have this [mod](https://ls-portal.eu/de/veenhuis-premium-integral-pack-v1-0-2/) in connection with "manual coupling" on. The problem I have is that the attachments on the barrel can no longer be disconnected.
- lower the device / if I then press "v", this activates
Do you have a solution or trick?

Thanks before and greetings

**Comment by Larman** [comment]
Exactly the same here

**Comment by CCL1106** [comment]
I have found a trick. but forgot it. 
But i had trouble with removing the tanker 🤔 
try to disconnect the tanker and then the attachment, and connecting tanker back

**Comment by stijnwop** [comment]
Pushed a fix.

**Comment by Alagoss** [comment]
Can confirm the fix.

**Comment by CCL1106** [comment]
![fsScreen_2020_04_19_13_03_47](https://user-images.githubusercontent.com/41755511/79686123-48d93880-823e-11ea-8208-66ca1538fc27.png)
default tanker and implement

if I want to detach it lowered, the shown error occurs. need to detach the tanker from the tractor, than its possible.

How to reproduce:
buy, tractor, tanker and td12, attach it, lower td 12 and try to detach it, this wont work, as the implement is turned on, as you can see here:
![fsScreen_2020_04_19_13_06_10](https://user-images.githubusercontent.com/41755511/79686161-8d64d400-823e-11ea-9981-cb8574294a4e.png)
I only can detach it, if its not lowered

**Comment by CCL1106** [comment]
works fine now 👍

**Comment by Black4Howk** [comment]
Hi stijnwop, thank you for the quick implementation.
Stay healthy and have a nice day. ;O)
