### ISSUE TITLE
DynamicHoses refactor

### ISSUE THREAD

**Issue by stijnwop** [stijnwop/manualAttach#7]
Currently includes:

- [x] Add ISOBUS type
- [x] Code cleanup and refactor
- [x] Support objectChange on attacherVehicle. (see feature request #6)

**Comment by stijnwop** [comment]
Any ideas on what the ISO Bus should do?

**Comment by deutzfahraustria** [comment]
Not sure if it's possible without thousands lines of code, but how about disabling the fillLevel in the hud? So if it uses fillable spec and Isobus is not attached it won't show the fillLevel

**Comment by deutzfahraustria** [comment]
line 110 in fillable spec might be useful for that, because there's already a way to hide the fillLevel in hud:   entry.showOnHud = Utils.getNoNil(getXMLBool(self.xmlFile, key .. "#showOnHud"), true);

**Comment by stijnwop** [comment]
Added the option to add ISOBus hoses.. it will disable the fillInformation if not connected. Might want to test it.

**Comment by stijnwop** [comment]
Everything is added, expect some backward compatibility fixes are needed to let the new dynamic hose scripts work in combination with the older ones.
