### ISSUE TITLE
Issue with mod

### ISSUE THREAD

**Issue by Horozor** [stijnwop/manualAttach#71]
Hey. Today I tried to use a mod from custom modding [https://www.facebook.com/custom.mdg/posts/2170220859684019](url) (Great Plains YP2425A with fertilizer tank SML1000) but the planter does not work. Hoses are attached but it is not possible to open the planter, and it also feels that the brakes are locked, as if the hoses were not connected. I understand that there can be problems with mods, but if there is an opportunity to fix it, I ask you to do it. I am very grateful for your work, I can not imagine how to play now without your mod.
Log file without errors

**Comment by KITT3000** [comment]
The problem is not with any mod. You just don't have all the tools you need. Connect to a tractor (which supports an additional tool pipe) e.g. Kuhn TF 1512 and the problem will disappear.

**Comment by Horozor** [comment]
@KITT3000 
You're right .. However, this makes it impossible to use the planter without Kuhn TF 1512. Well, have to look for another solution

**Comment by KITT3000** [comment]
@Horozor Only that technically you shouldn'tt be able to use this seeder without such a tank, it has a connection to such a tank so it should be connected. In the same way, e.g. you can't use Kuhn BTF 4000 without Kuhn TF 1512.

**Comment by Horozor** [comment]
@KITT3000 
Yes, that helped. Thanks. I did not notice the difference between the standard planter and the mod, I thought that only the fertilizer tank was added to the mod

**Comment by EradicationGod** [comment]
Same issue here with the John Deere 750A 3m/6m mod from CyrilModding88.

I already posted on this in the Giants forum, so I'm not double posting it here as well.
Would like some more insight on this though...

Thanks and keep up the good work.
