### ISSUE TITLE
Suggestion for multiplayer servers

### ISSUE THREAD

**Issue by NonoTwingo** [stijnwop/manualAttach#72]
First of all i would like to thank you ! This is my favorite Farming mod ! Giving so much more realism !

However i only upload this mod on local games. As not everyone feels concerned with it on multiplayer servers, would it be great to add it as a free option at the shop configurator for every tractor? To get the mod on server but only for players whom add this option. Fox example the guidance steering mod works like this.

Thank you again and sorry if my suggestion is not posted in the right section, that is the first time i log in Github

**Comment by stijnwop** [comment]
For GPS it makes more sense to make it vehicle based.. that's why I did it.

At the moment I don't think this option will be a thing as it's gameplay choice.. either play with it or not.

So you need to get to a consensus with your MP mated.

**Comment by NonoTwingo** [comment]
I would have say Autoload (which is a better example) but I understand your point. Thank you for your answer. Keep up the good work!

Arnaud
