### ISSUE TITLE
Not able to attach hoses (MP)

### ISSUE THREAD

**Issue by VenoushCZ** [stijnwop/manualAttach#73]
Hi!

**Scenario**: MP Dedi, FS19_horschPronto6AS.zip _https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=155181&title=fs2019_

**Problem**: Not able to attach hoses. Sound is playing OK. If I connect the seed bin Partner 1600FT in front, then the big seed hose is connected with Z key. Hoses stay disconnected.

Thank you

V.

**Comment by CCL1106** [comment]
also happens in SinglePlayer, Hud shows input to connect PTO, even there is no

**Comment by stijnwop** [comment]
PTO thing is not so weird as that back hose is done over a PTO entry (probably due to skinning).

**Comment by stijnwop** [comment]
Alright looked into the mod.

Isn't a MA issue but the planter actually isn't ingamed correctly.

Try it without MA the hoses also don't attach.
![fsScreen_2020_05_01_12_45_56](https://user-images.githubusercontent.com/12030020/80800429-b889e480-8ba9-11ea-8a18-dc39b601653b.png)

**Comment by stijnwop** [comment]
[FS19_horschPronto6AS.zip](https://github.com/stijnwop/manualAttach/files/4563726/FS19_horschPronto6AS.zip)

Replace the xml files from the mod with those from above.. that solves it.

**Comment by VenoushCZ** [comment]
Thank you for solving this for me! :-)

The difference is in the indices, right? Tho original version had the front indices too if I understand it correctly?

_<hose inputAttacherJointIndices="1 2"_ 


Just want to be sure for the next time so that I would not bother you if I can solve it by myself.


thnx



VenoushCZ

**Comment by stijnwop** [comment]
Jup indeed the hoses where not set to both attacher joints. So those didn't attach as by xml they where not ment for the tractor 

Make sure to update to the latest GitHub version tho.. added some checks for the PTOs :)
