### ISSUE TITLE
Pavelli Pack v1.0.0.0 FS19 not able to disconnect.

### ISSUE THREAD

**Issue by Pascal0997** [stijnwop/manualAttach#74]
Version Manual Attach: 1.1.0.0
Version Pavelli Pack: 1.0.0.0

I can't disconnect the Pavelli trailer from my tractor. When attaching it skips the hydraulic step.
I tried it with different tractors and it didn't work with any of them.

Thank you for this great mod.

**Comment by KITT3000** [comment]
Confirm, the only error that is repeated in the LOG:
`2020-05-01 13:01 Error: Running LUA method 'update'.
2020-05-01 13:01 mods/MP_UserB4D/FS19_manualAttach/src/ManualAttach.lua:491: attempt to call method 'disconnectHoses' (a nil value)`

**Comment by stijnwop** [comment]
Well that thing seems to be enterable for some reason, added support for it.

**Comment by KITT3000** [comment]
I confirm, it's ok now.

**Comment by Pascal0997** [comment]
Thank you very much for the quick response and fix.
