### ISSUE TITLE
LUA callstacks and errors

### ISSUE THREAD

**Issue by zfsdhyrhfhgdrtys** [stijnwop/manualAttach#76]
Hey Wopster, first of all, great work mate,keep it up!
Now, after updating Manual Attach and using it with the latest Hof_Bergmann map version 1.00.6 i encountered a lot of LUA callstacks and errors.I am attaching the log.txt, i am lost as to what might be the issues.If you have the time, please take a look and let me know if the errors are on my side or something with the mod.Thanks in advance mate!

[lua error.txt](https://github.com/stijnwop/manualAttach/files/4569803/lua.error.txt)

**Comment by stijnwop** [comment]
Could you give me some more context with what you're trying to attach?
Also a FULL log helps.

Well, tbh with you also try it without hof bergmann as that map has so much stuff going on that will most likely conflict with everything. 

As the error suggest it not being Manual Attach issue but rather an issue with vehicles not being deleted correctly or some kind of other mod messing around with attacher joints of vehicles.

**Comment by KITT3000** [comment]
For me there is no error, and I have been playing MP on this map for several hours.

**Comment by zfsdhyrhfhgdrtys** [comment]
Sorry for taking so long to respond to this!
I have found out the issue was with the latest update from CSZ tools pack, 1.4.3.
I have since reverted back to 1.4.2 and the issues are gone.
Thanks for looking into it Wopster and thank you KITT3000 for your response mate!
Have a nice day fellas!
