### ISSUE TITLE
Problem with Hof Bergmann and manualAttach

### ISSUE THREAD

**Issue by BlackBox1996** [stijnwop/manualAttach#77]
Hello Stijnwop,

do jo know about the Problem between manualAttach und Hof Bergmann V1.0.0.6?

Unfortunately, the function milk by bucket or the water withdrawal at the tap no longer works. Do you know a workaroud for this?

I would like to send you the log, but it is error free and without warning. Problem occurs with multiple users.

Br

Lukas

**Comment by KITT3000** [comment]
The problem are buildings/objects that are "vehicles". They have vehicle specializations through which MA activates in them causing strange problems.

**Comment by BlackBox1996** [comment]
Do you know a workaround for that?

**Comment by BlackBox1996** [comment]
heyho

with this Version it just work fine

https://github.com/stijnwop/manualAttach/releases/download/2.0.1.1/FS19_ManualAttach.zip

**Comment by UserB4D** [comment]
You're right, this version: https://github.com/stijnwop/manualAttach/releases/download/2.0.1.1/FS19_ManualAttach.zip works.
Is it possible that the bucket can be filled in the latest version?

**Comment by KITT3000** [comment]
@BlackBox1996 replace these files and everything will work on the latest MA version
[FS19_HofBergmann.zip](https://github.com/stijnwop/manualAttach/files/4658985/FS19_HofBergmann.zip)

**Comment by stijnwop** [comment]
So as discussed with KITT3000, I can't and won't fix this.

This is such an edge case scenario that is more an issue of that map, better said only the issue of that bucket.

If you managed to make a bucket that runs on vehicle specializations without only using what you actually need you ask for problems. Which is the case here, I can't adapt to things that run on vehicle specialization but are not vehicles or not using it.

So my advice in general is, if you make a 'special' vehicle.. only take the bare minimum.
