### ISSUE TITLE
Harvester headers not attaching/working

### ISSUE THREAD

**Issue by Regen752** [stijnwop/manualAttach#82]
Unsure if other are having this issue but harvester headers are attaching like in vanilla and not working.

When I disabled this mod the harvester worked fine.

**Comment by stijnwop** [comment]
You can attach the header in cab like in real life. (It's in the readme..)

But you have to jump out in order to attach the PTOs and hydraulics.

**Comment by Regen752** [comment]
My bad, the header attaches alright in the cab, but when I get out there is no option to attach PTO or hydraulics. I've had this issue with the TX32 and MF Activa 7347.

**Comment by KITT3000** [comment]
Maybe it's the same problem as in #61 and #64

**Comment by stijnwop** [comment]
Not sure what problem he's facing, but it works fine here.

![fsScreen_2020_07_09_10_42_09](https://user-images.githubusercontent.com/12030020/87018049-04bc5b00-c1d1-11ea-9814-4a50c2e67a50.png)
![fsScreen_2020_07_09_10_42_16](https://user-images.githubusercontent.com/12030020/87018058-05ed8800-c1d1-11ea-812b-c3e99ff7ee14.png)

You have to walk up close to the attacher.. and attach the PTO. Same counts for the TX, but that will require the hydraulics.

**Comment by Regen752** [comment]
Hi,

Yes you guys solved it. I didnt realise you have to walk right in there to get the attach button to show.

Thanks guys
