### ISSUE TITLE
Cannot disconnect Edge Field Roller (2.0.0.0) after connecting

### ISSUE THREAD

**Issue by TelluriumCrystal** [stijnwop/manualAttach#85]
Manual Attach version: 1.1.0.0
Edge Field Roller version: 2.0.0.0

To reproduce:

1. Connect Edge Field Roller to a tractor (note hoses auto connect)
2. Attempt to disconnect hoses, hoses remain connected and below error log entries are generated
3. Attempt to disconnect Edge Field Roller from tractor, get prompt "Detach Hoses of EDGE Industries 3 Meters First" (specific text depends on version of Edge Field Roller used)

Relevant error log lines:
```
2020-09-11 08:35 Error: Running LUA method 'update'.
2020-09-11 08:35 C:/Users/admin/Documents/My Games/FarmingSimulator2019/mods/FS19_manualAttach/src/ManualAttach.lua:502: attempt to call method 'disconnectHoses' (a nil value)
```

This appears to be a duplicate of Issue #74 which is caused because the Edge Field Rollers are enterable (seems kinda silly but has been useful in a couple instances). Should be fixable using the same method. I might even try to do it myself but I'm not super familiar with FS lua modding so no promises.

**Comment by stijnwop** [comment]
Hey, where can I find this Edge Field Roller mod?

Want to check the vehicle type of it.

**Comment by TelluriumCrystal** [comment]
https://www.farming-simulator.com/mod.php?mod_id=134740

**Comment by stijnwop** [comment]
Added support for it.

**Comment by TelluriumCrystal** [comment]
Thanks. Do you know if/when these changes will be pushed to Modhub or will I need to use the dev version from this repository?
