### ISSUE TITLE
Cannot disconnect CanAGRO 926 VT-HK belt/auger after connecting

### ISSUE THREAD

**Issue by dziuch** [stijnwop/manualAttach#86]
Manual Attach version: 1.1.0.0 and current master branch
CanAGRO 926 VT-HK version: [1.0.0.0](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=172351&title=fs2019)

Similar to issues #85 and #74 the CanAgro auger cannot be disconnected after connecting. I'm assuming it's because it has connectionHoses that ingame belts don't have.

I made it work by adding the following code after line 691 in `src/ManualAttach.lua`:
`or SpecializationUtil.hasSpecialization(ConveyorBelt, typeEntry.specializations)`

**Comment by Rensiur** [comment]
After implementing the suggested fix the following warning and endless loading loop appears.

Message:
2020-11-10 22:19 Error: Running LUA method 'loadSharedI3DFileFinished'.
2020-11-10 22:19 I:/FS19_Mods/mods/FS19_manualAttach/src/vehicle/ManualAttachConnectionHoses.lua:175: attempt to index local 'spec' (a nil value)

**Comment by dziuch** [comment]
You mean during loading a save or in what situation? It works fine here, so please provide more info.

**Comment by Rensiur** [comment]
After implementing the line as you described I get teh respective error whgen trying to load my map. I also have regular problems trying to unhook implements, always being asked to lower them, which is nonsense for Seeding units and the like . So maybe some issue on my side.
