### ISSUE TITLE
Cannot disconnect the (mod) Jenz BA 725 D

### ISSUE THREAD

**Issue by Gordon-Dry** [stijnwop/manualAttach#89]
This mod*:
https://www.farming-simulator.com/mod.php?lang=en&mod_id=185792&title=fs2019
https://www.modhoster.de/mods/jenz-ba-725-d

has an issue with manualAttach.
On each try to disconnect the cables with "Y" this is written to the log:

Error: Running LUA method 'update'.
User/Documents/My Games/FarmingSimulator2019/mods/FS19_manualAttach/src/ManualAttach.lua:502: attempt to call method 'disconnectHoses' (a nil value)

*that mod is better than the vanilla version which is unfinished

**Comment by Gordon-Dry** [comment]
It did not work, same behaviour, nearly same log entry:
Error: Running LUA method 'update'.
User/Documents/My Games/FarmingSimulator2019/mods/FS19_manualAttach/src/ManualAttach.lua:507: attempt to call method 'disconnectHoses' (a nil value)

**Comment by stijnwop** [comment]
Hey,

I assume this mod is enterable too?

**Comment by Gordon-Dry** [comment]
Yes
