### ISSUE TITLE
Compatibility issue with Zunhammer Fant

### ISSUE THREAD

**Issue by jason0611** [stijnwop/manualAttach#93]
Hi Wopster,

at first thank you very much for this really important and fine mod! :-)

Unfortunately there seems to be a issue using the new Zunhammer Fant: If it is attached to a tractor and after that a slurry tank is attached, the hoses/pto can't be connected and the whole thing can't be disconnected any more without deactivating manualAttach first.

I tested it in Single Player Mode on Felabrunn with only Manure System, Manual Attach and Zunhammer Fant enabled.

[log.txt](https://github.com/stijnwop/manualAttach/files/6005907/log.txt)
![fsScreen_2021_02_18_22_06_27](https://user-images.githubusercontent.com/12356451/108421782-f5f15880-7235-11eb-9d7a-3caa6fa174cd.png)
![fsScreen_2021_02_18_22_06_40](https://user-images.githubusercontent.com/12356451/108421820-01448400-7236-11eb-9fa2-0c4fc7da8c23.png)

Kind regards,
Martin/Jason06

**Comment by stijnwop** [comment]
Hey, thanks! :)

It sure works on my end, however you need to move a bit closer to the wheels for example to get inrange of the correct attacher. 

https://drive.google.com/open?id=16IpSt6hpbjCuzFV3JHSKOjfGF8n2hJ0f

**Comment by jason0611** [comment]
Hi Wopster,

it's a little bit tricky, but it works. Thank you for the hint. :-)
